services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - admin-service
      - order-service

  user-service:
    build:
      context: ./user-service
      dockerfile: build/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - user-db
  
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  admin-service:
    build:
      context: ./admin-service
      dockerfile: build/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - admin-db
      - item-service

  admin-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admindb
    ports:
      - "5433:5432"
    volumes:
      - admin-db-data:/var/lib/postgresql/data

  item-service:
    build:
      context: ./item-service
      dockerfile: build/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - item-db

  item-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: item
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itemdb
    ports:
      - "5434:5432"
    volumes:
      - item-db-data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
      dockerfile: build/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - order-db
      - order-outbox-db
      - nats
  
  order-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
  
  order-outbox-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: order-outbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-outboxdb
    ports:
      - "5436:5432"
    volumes:
      - order-outbox-db-data:/var/lib/postgresql/data

  payment-service:
    build:
      context: ./payment-service
      dockerfile: build/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

volumes:
  user-db-data:
  admin-db-data:
  item-db-data:
  order-db-data:
  order-outbox-db-data: