services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: build/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - user-db
  
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  admin-service:
    build:
      context: ./admin-service
      dockerfile: build/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - admin-db

  admin-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admindb
    ports:
      - "5433:5432"
    volumes:
      - admin-db-data:/var/lib/postgresql/data
  

volumes:
  user-db-data:
  admin-db-data: