basePath: /
definitions:
  models.Item:
    properties:
      amount:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  models.ItemBoughtResponse:
    properties:
      bought:
        type: integer
      item_in_store:
        $ref: '#/definitions/models.Item'
      message:
        type: string
    type: object
  models.ItemDeliveredResponse:
    properties:
      delivered:
        type: integer
      item_in_store:
        $ref: '#/definitions/models.Item'
      message:
        type: string
    type: object
  models.ItemResponse:
    properties:
      item:
        $ref: '#/definitions/models.Item'
      message:
        type: string
    type: object
  models.ItemWithNewPriceResponse:
    properties:
      item:
        $ref: '#/definitions/models.Item'
      message:
        type: string
      old_price:
        type: number
    type: object
  models.StatusResponse:
    properties:
      message:
        type: string
      name:
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: API for interacting with items in storage.
  title: Item Service
  version: "1.0"
paths:
  /v1/items/add:
    post:
      description: Add a new item.
      parameters:
      - description: Item name which you want to add
        in: query
        name: name
        required: true
        type: string
      - description: Cost of the item
        in: query
        name: price
        required: true
        type: number
      - description: Amount of the item in stock
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusResponse'
      tags:
      - Items
  /v1/items/buy:
    post:
      description: Makes item purchase.
      parameters:
      - description: Item name which you want to buy
        in: query
        name: name
        required: true
        type: string
      - description: Amount of the item to buy
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemBoughtResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusResponse'
      tags:
      - Items
  /v1/items/deliver:
    post:
      description: Makes delivery for item.
      parameters:
      - description: Item name which you want to deliver
        in: query
        name: name
        required: true
        type: string
      - description: Amount of the item to deliver
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemDeliveredResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusResponse'
      tags:
      - Items
  /v1/items/remove:
    post:
      description: Remove an item.
      parameters:
      - description: Item name which you want to remove
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusResponse'
      tags:
      - Items
  /v1/items/update-price:
    post:
      description: Change price for item.
      parameters:
      - description: Item name which you want to change price for
        in: query
        name: name
        required: true
        type: string
      - description: New price of the item
        in: query
        name: price
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ItemWithNewPriceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusResponse'
      tags:
      - Items
swagger: "2.0"
