basePath: /
definitions:
  dto.StatusResponse:
    properties:
      message:
        type: string
      user_id:
        type: string
    type: object
  dto.UserRegistered:
    properties:
      is_registered:
        type: boolean
      user_id:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for interacting with users.
  title: User Service
  version: "1.0"
paths:
  /v1/users/{userID}:
    get:
      description: Checks if user is registered.
      parameters:
      - description: User ID which you want to check
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserRegistered'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.StatusResponse'
swagger: "2.0"
