basePath: /
definitions:
  dto.StatusResponse:
    properties:
      message:
        type: string
      user:
        type: string
    type: object
  dto.UserRegistered:
    properties:
      is_registered:
        type: boolean
      user:
        type: string
    type: object
  models.User:
    properties:
      balance:
        type: number
      name:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for interacting with users.
  title: User Service
  version: "1.0"
paths:
  /v1/users/{user}:
    get:
      description: Checks if user is registered.
      parameters:
      - description: User which you want to check
        in: path
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserRegistered'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - Users
  /v1/users/balance:
    get:
      description: Returns user's balance.
      parameters:
      - description: User whose balance you want to get
        in: query
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - Users
  /v1/users/change-balance:
    post:
      description: Changes the balance of a registered user.
      parameters:
      - description: User whose balance you want to change
        in: query
        name: name
        required: true
        type: string
      - description: New balance of the user
        in: query
        name: balance
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - Users
  /v1/users/register:
    post:
      description: Registers a new user.
      parameters:
      - description: User which you want to register
        in: query
        name: name
        required: true
        type: string
      - description: Balance of the user
        in: query
        name: balance
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - Users
swagger: "2.0"
